// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHello2Data, GetHello2Responses, GetHelloData, GetHelloResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Simple greeting endpoint
 */
export const getHello = <ThrowOnError extends boolean = false>(options?: Options<GetHelloData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHelloResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Echo back path id and optional query
 */
export const getHello2 = <ThrowOnError extends boolean = false>(options: Options<GetHello2Data, ThrowOnError>) => {
    return (options.client ?? client).get<GetHello2Responses, unknown, ThrowOnError>({
        url: '/echo/{id}',
        ...options
    });
};
