// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type HelloResponseDto = {
  /**
   * Greeting message
   */
  message: string;
};

export type EchoResponseDto = {
  /**
   * Echoed path id
   */
  id: string;
  /**
   * Echoed query value (if provided)
   */
  q?: string;
};

export type GetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetHelloResponses = {
  /**
   * Returns a greeting message
   */
  200: HelloResponseDto;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type GetHello2Data = {
  body?: never;
  path: {
    /**
     * Identifier to echo
     */
    id: string;
  };
  query?: {
    /**
     * Optional query text to echo
     */
    q?: string;
  };
  url: "/echo/{id}";
};

export type GetHello2Responses = {
  /**
   * Echoed data
   */
  200: EchoResponseDto;
};

export type GetHello2Response = GetHello2Responses[keyof GetHello2Responses];
